version: '3.8'
services:
  appseed-app:
    container_name: appseed_app
    restart: always
    build: .
    networks:
      - db_network
      - web_network
    environment:
      - DATABASE_URL=${DATABASE_URL}
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - .:/app
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - my_sqlite_data:/app/db
    networks:
      - web_network
    depends_on:
      - appseed-app
volumes:
  static_volume:
  media_volume:
  my_sqlite_data:
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
